const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("🚀 Deploying CertificateRegistry contract...");

    // Get deployer account
    const [deployer] = await hre.ethers.getSigners();
    console.log("📝 Deploying with account:", deployer.address);

    // Check balance
    const balance = await hre.ethers.provider.getBalance(deployer.address);
    console.log("💰 Account balance:", hre.ethers.formatEther(balance), "MATIC");

    // Deploy contract
    const CertificateRegistry = await hre.ethers.getContractFactory("SoulboundCertificateRegistry");
    const registry = await CertificateRegistry.deploy();

    await registry.waitForDeployment();
    const contractAddress = await registry.getAddress();

    console.log("✅ CertificateRegistry deployed to:", contractAddress);
    console.log("🔗 Network:", hre.network.name);
    console.log("⛓️  Chain ID:", hre.network.config.chainId);

    // Save contract address to backend config
    const envPath = path.join(__dirname, "../../backend/.env.contract");
    const envContent = `# Auto-generated by deployment script
CONTRACT_ADDRESS=${contractAddress}
CHAIN_ID=${hre.network.config.chainId}
NETWORK=${hre.network.name}
DEPLOYED_AT=${new Date().toISOString()}
`;

    fs.writeFileSync(envPath, envContent);
    console.log("📄 Contract address saved to:", envPath);

    // Save deployment info
    const deploymentInfo = {
        contractAddress,
        network: hre.network.name,
        chainId: hre.network.config.chainId,
        deployer: deployer.address,
        deployedAt: new Date().toISOString(),
        blockNumber: await hre.ethers.provider.getBlockNumber()
    };

    const deploymentPath = path.join(__dirname, "../deployments.json");
    let deployments = {};

    if (fs.existsSync(deploymentPath)) {
        deployments = JSON.parse(fs.readFileSync(deploymentPath, "utf8"));
    }

    deployments[hre.network.name] = deploymentInfo;
    fs.writeFileSync(deploymentPath, JSON.stringify(deployments, null, 2));

    console.log("\n📋 Deployment Summary:");
    console.log("   Contract:", contractAddress);
    console.log("   Network:", hre.network.name);
    console.log("   Explorer:", getExplorerUrl(hre.network.name, contractAddress));

    // Wait for block confirmations before verification
    if (hre.network.name !== "hardhat" && hre.network.name !== "localhost") {
        console.log("\n⏳ Waiting for block confirmations...");
        await registry.deploymentTransaction().wait(5);
        console.log("✅ Confirmed!");

        console.log("\n📝 To verify contract, run:");
        console.log(`   npx hardhat verify --network ${hre.network.name} ${contractAddress}`);
    }
}

function getExplorerUrl(network, address) {
    const explorers = {
        mumbai: `https://mumbai.polygonscan.com/address/${address}`,
        polygon: `https://polygonscan.com/address/${address}`,
        hardhat: "N/A (local network)",
        localhost: "N/A (local network)"
    };
    return explorers[network] || "Unknown network";
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("❌ Deployment failed:", error);
        process.exit(1);
    });
